---
abstract: "an extension of Params::Validate for using Moose's types"
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.21
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Params-Validate
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Devel::Caller: 0
  Moose: 0.58
  Params::Validate: 0.88
  Scalar::Util: 0
  Sub::Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://code2.0beta.co.uk/moose/svn/MooseX-Params-Validate
version: 0.13
