---
abstract: 'an extension of Params::Validate for using Moose''s types'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Params-Validate
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Moose: 0.58
  Params::Validate: 0.88
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
