---
name: MooseX-Params-Validate
version: 0.02
author:
  - 'Stevan Little E<lt>stevan.little@iinteractive.comE<gt>'
abstract: an extension of Params::Validate for using Moose's types
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Moose: 0.17
  Params::Validate: 0.88
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  MooseX::Params::Validate:
    file: lib/MooseX/Params/Validate.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
